parameters:
    pim_events_api.job.job_parameters.constraint_collection_provider.deliver_outer_event.class: Frmoda\Bundle\EventsApiBundle\Job\JobParameters\DeliverOuterEventConstraintCollectionProvider
    pim_events_api.tasklet.deliver_outer_event.class: Frmoda\Bundle\EventsApiBundle\Job\DeliverOuterEventTasklet
    pim_events_api.deliver_outer_event_to_consumer.job_type: 'deliver_outer_event_to_consumer'
    pim_events_api.deliver_outer_event_to_consumer.job_name: 'deliver_outer_event_to_consumer'
    pim_events_api.deliver_outer_event_to_consumer.tasklet_name: 'deliver_outer_event_to_consumer'
    pim_events_api.deliver_outer_event_to_consumer.connector_name: 'deliver_outer_event_to_consumer'

services:
    pim_events_api.job.job_parameters.constraint_collection_provider.deliver_outer_event:
        class: '%pim_events_api.job.job_parameters.constraint_collection_provider.deliver_outer_event.class%'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }

    pim_events_api.job.job_parameters.default_values_provider.deliver_outer_event_to_consumer:
        class: '%akeneo_batch.job.job_parameters.empty_values_provider.class%'
        arguments:
            -
                - '%pim_events_api.deliver_outer_event_to_consumer.job_name%'
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }

    pim_events_api.tasklet.deliver_outer_event:
        class: '%pim_events_api.tasklet.deliver_outer_event.class%'
        arguments:
            - '@pim_events_api.transport.default'
        public: false

    pim_events_api.step.deliver_outer_event:
        class: '%pim_connector.step.tasklet.class%'
        arguments:
            - '%pim_events_api.deliver_outer_event_to_consumer.tasklet_name%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_events_api.tasklet.deliver_outer_event'
        public: false

    pim_events_api.job.deliver_outer_event_to_consumer:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%pim_events_api.deliver_outer_event_to_consumer.job_name%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@pim_events_api.step.deliver_outer_event'
        public: false
        tags:
            -
                name: akeneo_batch.job
                connector: '%pim_events_api.deliver_outer_event_to_consumer.connector_name%'
                type: '%pim_events_api.deliver_outer_event_to_consumer.job_type%'
